import type { InvoiceRecord, InvoiceItem, PaymentMethod } from "./types";

const currencies: InvoiceRecord["currency"][] = ["USD", "EUR", "GBP", "CAD", "MXN", "AUD", "JPY", "BRL"];
const industries = ["Northstar Creative", "Juniper Labs", "Orbit & Oak", "Mosaic Studio", "Blue Harbor Co.", "Cedarline", "Goodlight Media", "Atlas Workshop", "Lumen Works", "Pine & Pixel"];
const clients = ["Avery Chen", "Maya Rodriguez", "Noah Williams", "Sofia Patel", "Elliot Brooks", "Camila Santos", "Theo Martin", "Riley Kim", "Morgan Blake", "Jamie Foster"];
const projects = ["Brand identity refresh", "Q3 product strategy", "Website redesign", "Launch campaign", "Operations consulting", "Editorial photo series", "Mobile app prototype", "Retail experience", "Content system", "Annual support plan"];
const colors = ["#17b6d4", "#6757d9", "#e56b4b", "#2d9b72", "#d49b2a"];
const id = (n: number, suffix = "") => `demo-${n}-${suffix || "invoice"}`;
const date = (n: number) => `2026-${String((n % 9) + 1).padStart(2, "0")}-${String((n * 3 % 25) + 1).padStart(2, "0")}`;
const address = (n: number) => ({ line1: `${100 + n * 17} Market Avenue`, line2: n % 2 ? `Suite ${200 + n}` : "", city: ["Austin", "Toronto", "London", "Miami", "Seattle"][n % 5], region: ["TX", "ON", "LDN", "FL", "WA"][n % 5], postalCode: ["78701", "M5V 2T6", "EC2A 4BX", "33101", "98101"][n % 5], country: n % 4 === 1 ? "Canada" : n % 4 === 2 ? "United Kingdom" : "United States" });

export function createDemoInvoices(): InvoiceRecord[] {
  return industries.slice(0, 5).map((businessName, n) => {
    const currency = currencies[n % currencies.length];
    const items: InvoiceItem[] = Array.from({ length: 2 + (n % 3) }, (_, i) => ({ id: id(n, `item-${i}`), description: `${projects[n]} — ${["Discovery", "Design", "Implementation", "Review"][i % 4]}`, category: ["Strategy", "Design", "Development", "Production"][i % 4], quantity: String(i + 1), unitLabel: ["hour", "day", "project", "license"][i % 4], unitPriceMinor: (280 + n * 47 + i * 325) * 100, discountBasisPoints: i === 1 && n % 2 === 0 ? 500 : 0, taxable: i !== 0, sortOrder: i }));
    const status: InvoiceRecord["status"] = (["draft", "issued", "paid", "void"] as const)[n % 4];
    const paymentMethods: PaymentMethod[] = n % 3 === 0 ? [{ id: id(n, "paypal"), type: "paypal", label: "PayPal", value: `payments+${n}@wzxu.example`, instructions: "Please include the invoice number in your payment note." }] : n % 3 === 1 ? [{ id: id(n, "zelle"), type: "zelle", label: "Zelle", value: `billing${n}@wzxu.example`, instructions: "Zelle payments are typically confirmed within one business day." }] : [{ id: id(n, "custom"), type: "custom", label: "Bank transfer", value: `WZXU-DEMO-${1000 + n}`, instructions: "Use the invoice number as your transfer reference." }];
    const issueDate = date(n + 1); const totalEstimate = items.reduce((sum, item) => sum + Number(item.quantity) * item.unitPriceMinor, 0);
    return { id: id(n), schemaVersion: 1, createdAt: `${issueDate}T09:00:00.000Z`, updatedAt: `${issueDate}T09:00:00.000Z`, status, business: { name: businessName, contactName: ["Jordan Lee", "Taylor Morgan", "Casey Rivera"][n % 3], email: `hello${n}@${businessName.toLowerCase().replace(/[^a-z]/g, "")}.example`, phone: `+1 (555) 01${String(n).padStart(2, "0")}`, website: `https://www.${businessName.toLowerCase().replace(/[^a-z]/g, "")}.example`, taxId: `DEMO-TAX-${7000 + n}`, address: address(n) }, client: { name: clients[n], company: `${["Solstice", "Verde", "Kite", "Willow", "Hearth"][n % 5]} ${["Partners", "Market", "Group", "House"][n % 4]}`, email: `accounts${n}@client${n}.example`, phone: `+1 (555) 02${String(n).padStart(2, "0")}`, taxId: `CLIENT-DEMO-${8000 + n}`, reference: `PO-${2026}-${410 + n}`, address: address(n + 2) }, invoiceNumber: `DEMO-2026-${String(n + 1).padStart(4, "0")}`, issueDate, dueDate: date(n + 15), purchaseOrderNumber: `PO-${2026}-${410 + n}`, projectName: `${projects[n]} · Demo`, currency, items, adjustments: { discountType: n % 3 === 0 ? "percentage" : n % 3 === 1 ? "fixed" : "none", discountMinor: n % 3 === 1 ? Math.round(totalEstimate * 0.04) : 0, discountBasisPoints: n % 3 === 0 ? 750 : 0, taxLabel: n % 2 ? "VAT" : "Sales tax", taxBasisPoints: 500 + (n % 4) * 125, shippingMinor: n % 2 ? 0 : (35 + n * 8) * 100, shippingTaxable: n % 2 === 0, additionalFeeLabel: "Production fee", additionalFeeMinor: n % 3 === 2 ? 12500 : 0, additionalFeeTaxable: true, creditMinor: n % 4 === 0 ? 5000 : 0, depositMinor: status === "paid" || n % 3 === 0 ? Math.round(totalEstimate * 0.25) : 0, amountPaidMinor: status === "paid" ? Math.round(totalEstimate * 0.75) : 0 }, paymentMethods, notes: { notesToClient: `Thanks for partnering with ${businessName}. This fictional demo invoice showcases a complete client note.`, terms: "", lateFeeTerms: "A 1.5% monthly service charge may apply to balances more than 30 days overdue.", thankYouMessage: n % 2 ? "Thank you — we appreciate your partnership." : "Thank you for your business!", signatureName: ["Jordan Lee", "Taylor Morgan", "Casey Rivera"][n % 3], signatureTitle: ["Creative Director", "Principal Consultant", "Studio Lead"][n % 3] }, appearance: { templateId: n % 2 ? "midnight-creator" : "clean-professional", accentColor: colors[n % colors.length], pageSize: n % 3 === 0 ? "A4" : "LETTER", invoiceLocale: n % 4 === 2 ? "es-MX" : "en-US" } };
  });
}
